require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/dummy/**/*.rb'
    - 'vendor/bundle/**/*'

# This cop causes issues with Hashes
Style/ArrayCoercion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/ExampleLength:
  Max: 8

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
